### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by henrebotha**

### CODE REVIEW

**Review by olets — APPROVED** [review]
🦅👁️! Thank you

**Comment by olets** [comment]
Wow Vercel requiring authorization to build is a _great_ feature.

**Comment by henrebotha** [comment]
Yeah no kidding!

**Comment by olets** [comment]
Missed going through this repo when I added Community to https://github.com/olets/zsh-abbr and the docs site.

@henrebotha shall I have all-contributors add the documentation badge to your entry?

**Comment by olets** [comment]
Oh and bug reporting too 🙏 🏅  https://github.com/olets/zsh-abbr/issues/30

**Comment by henrebotha** [comment]
Yes please!

**Comment by olets** [comment]
Done, merged, deployed https://github.com/olets/zsh-abbr/pull/127

**Pull request merged**
